spring.application.name=spring-gift

#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.mode=never

# JWT setting
jwt.expiration=86400000

# JPA ??
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# H2 ?? (MySQL ?? ??)
spring.datasource.url=jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# DDL ?? ?? (?? ??? ??)
spring.jpa.hibernate.ddl-auto=create-drop



# ?? ???
erver.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

spring.config.import=optional:classpath:application-secret.properties