spring.application.name=spring-gift

#spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.mode=never

# JWT setting
jwt.secret=my-secret-key-for-gift-application-should-be-very-long-and-secure-2024
jwt.expiration=86400000

# JPA ??
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# H2 ?? (MySQL ?? ??)
spring.datasource.url=jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# DDL ?? ?? (?? ??? ??)
spring.jpa.hibernate.ddl-auto=create-drop

kakao.client-id=51d0bb3bf8791e6765fe07102c738d75
kakao.redirect-uri=http://localhost:8080